NAME = bonus

# C compiler
CC = clang-15
CFLAGS = -Wall -Wextra -Werror

SRCS = main.c \
		ft_atoi_base.c \
		ft_list_push_front.c \
		ft_list_size.c \
		# ft_list_remove_if.c \
		# ft_list_sort.c \

all:
	$(CC) $(CFLAGS) $(SRCS) -o $(NAME)

clean:
	@rm -rf $(NAME)
